### ISSUE TITLE
Not running locally

### ISSUE THREAD

**Issue by funykcheff** [priyanshumahey/AITalents-Sonean-Briefer#1]
@priyanshumahey thanks for the submission. can you please take a look, I cannot run it on 127.0.0.1:500
Page is continuously loading but nothing appears. do I do smth wrong? Thanks!

![image](https://user-images.githubusercontent.com/10008680/103900749-75005680-50f8-11eb-992f-1d893df69f71.png)

**Comment by priyanshumahey** [comment]
> @priyanshumahey thanks for the submission. can you please take a look, I cannot run it on 127.0.0.1:500
> Page is continuously loading but nothing appears. do I do smth wrong? Thanks!
> 
> ![image](https://user-images.githubusercontent.com/10008680/103900749-75005680-50f8-11eb-992f-1d893df69f71.png)

I'm not sure why thats the case, it's been able to run for our team just fine but perhaps that port is already being used. Try: flask run -h localhost -p 3000   
This will let you change the address of where it runs and it should work then!

Could you also try using %tb to allow us to see the full traceback in order to help you better?

**Comment by funykcheff** [comment]
It worked with 3000, thanks!
